name: Zabon
version: '${project.version}'
main: cucumbersaurus.zabon.Zabon
api-version: 1.18
authors: [ cucumbersaurus ]
description: test&zabon

commands:
  wasans:
    description: 와! 샌즈
    usage: 와! 샌즈
    aliases: [와샌즈]
    permission-message: 서버장한테 op 달라고 해
    permission: zabon.wasans
  effectmenu:
    description: 이펙트 창
    usage: /effectmenu
    permission: zabon.effectmenu
  guitest:
    description: gui 테스트하기
    usage: /guitest
    permission: zabon.guitest
  playerlocation:
    usage: /playerlocation,/pl
    aliases: [prl]
    permission: zabon.playerlocation
  zabon:
    description: 재산 관리 창 열기
    usage: /zabon, /zb
    aliases: [zb]
    permission: zabon.system.zabon
  bank:
    description: 은행 창 열기
    usage: /bank, /bk
    aliases: [bk]
    permission: zabon.system.bank
permissions:
  zabon.*:
    default: op
    children:
      zabon.wasans: true
      zabon.effectmenu: true
  zabon.playerlocation:
    default: true
  zabon.system.*:
    default: true
    children:
      zabon.system.zabon: true
      zabon.system.bank: true